name: Conditional env variable

on: [workflow_dispatch, push]

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! Path is $MYPATH"
        env:
          MYPATH: ${{ github.repository }}
          First_Name: Mona