# Simple build test in docker environment
name: Build test 
run-name: Build test run by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]  

  workflow_run:
    workflows: ["Docker image update"]
    branches:
      - 'main'
    
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to run tests for'
        required: false
        default: 'rd_rw612_bga'
        type: string
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/radimli/maestro_test:main
      volumes: 
        # TODO: Copy into the container instead?
        - ${{ github.workspace }}:/app/maestro
        #username: ${{ github.actor }}
        #password: ${{ secrets.PRIVATE_ACCESS_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize west
      run: |
        cd /app/maestro
        pwd
        ls -la
        west init -l . --mf west-freestanding.yml
        west update

    - name: Execute build tests
      run: |
        cd /app/maestro
        ls -la
        west --version
        west list -a
        #west twister --verbose --platform @${{ inputs.platform }} --integration --build-only --testsuite-root ../
        west twister --verbose --platform rd_rw612_bga --integration --build-only --testsuite-root ../
        cd ..
        ls -la
